# Generated by Django 6.0.3 on 2026-05-16 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.CreateModel(
            name='PhongTro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieu_de', models.CharField(max_length=255)),
                ('mo_ta', models.TextField()),
                ('gia_thue', models.DecimalField(decimal_places=0, max_digits=12)),
                ('dia_chi', models.CharField(max_length=500)),
                ('quan_huyen', models.CharField(max_length=100)),
                ('thanh_pho', models.CharField(default='TP.HCM', max_length=100)),
                ('dien_tich', models.FloatField(help_text='m²')),
                ('trang_thai', models.CharField(choices=[('cho_duyet', 'Chờ duyệt'), ('da_duyet', 'Đã duyệt'), ('tu_choi', 'Từ chối'), ('an', 'Ẩn')], default='cho_duyet', max_length=20)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('ngay_dang', models.DateTimeField(auto_now_add=True)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('chu_tro', models.ForeignKey(limit_choices_to={'role': 'host'}, on_delete=django.db.models.deletion.CASCADE, related_name='phong_tro', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-ngay_dang'],
            },
        ),
        migrations.CreateModel(
            name='AnhPhongTro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hinh_anh', models.ImageField(upload_to='phong_tro/')),
                ('la_anh_chinh', models.BooleanField(default=False)),
                ('thu_tu', models.IntegerField(default=0)),
                ('phong_tro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anh', to='accommodation.phongtro')),
            ],
            options={
                'ordering': ['thu_tu'],
            },
        ),
        migrations.CreateModel(
            name='ThongBao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loai', models.CharField(choices=[('duyet_tin', 'Duyệt tin'), ('tu_choi_tin', 'Từ chối tin'), ('binh_luan', 'Bình luận mới'), ('tin_nhan', 'Tin nhắn mới'), ('he_thong', 'Hệ thống')], max_length=20)),
                ('tieu_de', models.CharField(max_length=255)),
                ('noi_dung', models.TextField()),
                ('da_doc', models.BooleanField(default=False)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('nguoi_nhan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thong_bao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-ngay_tao'],
            },
        ),
        migrations.CreateModel(
            name='TinNhan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noi_dung', models.TextField()),
                ('thoi_gian', models.DateTimeField(auto_now_add=True)),
                ('da_doc', models.BooleanField(default=False)),
                ('nguoi_gui', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tin_nhan_gui', to=settings.AUTH_USER_MODEL)),
                ('nguoi_nhan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tin_nhan_nhan', to=settings.AUTH_USER_MODEL)),
                ('phong_tro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tin_nhan', to='accommodation.phongtro')),
            ],
            options={
                'ordering': ['thoi_gian'],
            },
        ),
        migrations.CreateModel(
            name='LuuPhong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_luu', models.DateTimeField(auto_now_add=True)),
                ('nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='luu_phong', to=settings.AUTH_USER_MODEL)),
                ('phong_tro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duoc_luu', to='accommodation.phongtro')),
            ],
            options={
                'unique_together': {('nguoi_dung', 'phong_tro')},
            },
        ),
        migrations.CreateModel(
            name='BinhLuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noi_dung', models.TextField()),
                ('danh_gia', models.IntegerField(choices=[(1, '1 sao'), (2, '2 sao'), (3, '3 sao'), (4, '4 sao'), (5, '5 sao')], default=5)),
                ('ngay_dang', models.DateTimeField(auto_now_add=True)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('nguoi_dung', models.ForeignKey(limit_choices_to={'role': 'tenant'}, on_delete=django.db.models.deletion.CASCADE, related_name='binh_luan', to=settings.AUTH_USER_MODEL)),
                ('phong_tro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='binh_luan', to='accommodation.phongtro')),
            ],
            options={
                'ordering': ['-ngay_dang'],
                'unique_together': {('phong_tro', 'nguoi_dung')},
            },
        ),
    ]
