# Generated by Django 6.0.3 on 2026-05-16 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0002_user_avatar_phongtro_anhphongtro_thongbao_tinnhan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phongtro',
            name='dien_tich',
        ),
    ]
