# Generated by Django 6.0.3 on 2026-05-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0003_remove_phongtro_dien_tich'),
    ]

    operations = [
        migrations.AddField(
            model_name='phongtro',
            name='dien_tich',
            field=models.FloatField(default=0, help_text='m²'),
            preserve_default=False,
        ),
    ]
